FROM golang:1.25-alpine

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy everything from root context
COPY . .

# Move to service directory
WORKDIR /app/services/auth

# Download dependencies
RUN go mod download

# Default command - use air for hot reloading
CMD ["air"]