// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package main

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UsersAuth struct {
	ID             pgtype.UUID        `json:"id"`
	Email          string             `json:"email"`
	Phone          string             `json:"phone"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
