// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package main

import (
	"context"
)

type Querier interface {
	CheckExistedUserByEmail(ctx context.Context, email string) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (UsersAuth, error)
	RegisterWithEmail(ctx context.Context, arg RegisterWithEmailParams) error
}

var _ Querier = (*Queries)(nil)
