// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckPhoneExists(ctx context.Context, email string) (bool, error)
	CheckProductExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckProductOwnership(ctx context.Context, arg CheckProductOwnershipParams) (bool, error)
	CheckPuchaseExist(ctx context.Context, purchaseid uuid.UUID) (bool, error)
	CheckSKUExistsByUser(ctx context.Context, arg CheckSKUExistsByUserParams) (CheckSKUExistsByUserRow, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Products, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) error
	CreateUserFromUserAuth(ctx context.Context, arg CreateUserFromUserAuthParams) (Users, error)
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAllProducts(ctx context.Context, arg GetAllProductsParams) ([]GetAllProductsRow, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error)
	GetPurchaseByID(ctx context.Context, purchaseid uuid.UUID) (Purchases, error)
	GetUserByAuthID(ctx context.Context, userAuthID uuid.UUID) (Users, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (Users, error)
	GetUserByPhone(ctx context.Context, phone string) (Users, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateProductQty(ctx context.Context, arg UpdateProductQtyParams) (int64, error)
	UpdatePurchaseStatus(ctx context.Context, arg UpdatePurchaseStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (Users, error)
	UpdateUserPhone(ctx context.Context, arg UpdateUserPhoneParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
