services:
  # API Gateway
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth-service
      - core-service
      - files-service
    restart: unless-stopped

  # Auth Service
  auth-service:
    build:
      context: ..
      dockerfile: services/auth/Dockerfile
    expose:
      - "${AUTH_PORT}"
    environment:
      - PORT=${AUTH_PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - main-db
    restart: unless-stopped

  # Core Service
  core-service:
    build:
      context: ..
      dockerfile: services/core/Dockerfile
    expose:
      - "${CORE_PORT}"
    environment:
      - PORT=${CORE_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - FILES_SERVICE_URL=${FILES_SERVICE_URL}
    depends_on:
      - main-db
    restart: unless-stopped

  # Files Service
  files-service:
    build:
      context: ..
      dockerfile: services/files/Dockerfile
    expose:
      - "${FILES_PORT}"
    environment:
      - PORT=${FILES_PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - main-db
    restart: unless-stopped

  # Main Database
  main-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - main_data:/var/lib/postgresql/data
      - ../migrations:/docker-entrypoint-initdb.d/:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  main_data:

networks:
  default:
    name: tutuplapak-network