// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UsersAuth struct {
	ID           pgtype.UUID      `json:"id"`
	Email        pgtype.Text      `json:"email"`
	Phone        pgtype.Text      `json:"phone"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
