// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Products struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Category  string    `json:"category"`
	Qty       int       `json:"qty"`
	Price     int       `json:"price"`
	Sku       string    `json:"sku"`
	FileID    uuid.UUID `json:"file_id"`
	UserID    uuid.UUID `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Users struct {
	ID                uuid.UUID          `json:"id"`
	Email             string             `json:"email"`
	Phone             *string            `json:"phone"`
	BankAccountName   *string            `json:"bank_account_name"`
	BankAccountHolder *string            `json:"bank_account_holder"`
	BankAccountNumber *string            `json:"bank_account_number"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UsersAuth struct {
	ID           uuid.UUID        `json:"id"`
	Email        *string          `json:"email"`
	Phone        *string          `json:"phone"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
