// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchases.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createPurchase = `-- name: CreatePurchase :exec
INSERT INTO purchases (
    id, sender_name, sender_contact_type, sender_contact_detail,
    purchased_items, payment_details, total_price
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePurchaseParams struct {
	ID                  uuid.UUID `json:"id"`
	SenderName          string    `json:"sender_name"`
	SenderContactType   string    `json:"sender_contact_type"`
	SenderContactDetail string    `json:"sender_contact_detail"`
	PurchasedItems      []byte    `json:"purchased_items"`
	PaymentDetails      []byte    `json:"payment_details"`
	TotalPrice          int32     `json:"total_price"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) error {
	_, err := q.db.Exec(ctx, createPurchase,
		arg.ID,
		arg.SenderName,
		arg.SenderContactType,
		arg.SenderContactDetail,
		arg.PurchasedItems,
		arg.PaymentDetails,
		arg.TotalPrice,
	)
	return err
}
