// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_auth.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkPhoneExists = `-- name: CheckPhoneExists :one
SELECT EXISTS(SELECT 1 FROM users_auth WHERE phone = $1) as exists
`

func (q *Queries) CheckPhoneExists(ctx context.Context, phone *string) (bool, error) {
	row := q.db.QueryRow(ctx, checkPhoneExists, phone)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createUserAuth = `-- name: CreateUserAuth :one
INSERT INTO users_auth (phone, password_hash)
VALUES ($1, $2)
RETURNING id, phone, password_hash, created_at
`

type CreateUserAuthParams struct {
	Phone        *string `json:"phone"`
	PasswordHash string  `json:"password_hash"`
}

type CreateUserAuthRow struct {
	ID           uuid.UUID        `json:"id"`
	Phone        *string          `json:"phone"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (CreateUserAuthRow, error) {
	row := q.db.QueryRow(ctx, createUserAuth, arg.Phone, arg.PasswordHash)
	var i CreateUserAuthRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAuthByID = `-- name: GetUserAuthByID :one
SELECT id, phone, password_hash, created_at
FROM users_auth
WHERE id = $1
`

type GetUserAuthByIDRow struct {
	ID           uuid.UUID        `json:"id"`
	Phone        *string          `json:"phone"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserAuthByID(ctx context.Context, id uuid.UUID) (GetUserAuthByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByID, id)
	var i GetUserAuthByIDRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserAuthByPhone = `-- name: GetUserAuthByPhone :one
SELECT id, phone, password_hash, created_at
FROM users_auth
WHERE phone = $1
`

type GetUserAuthByPhoneRow struct {
	ID           uuid.UUID        `json:"id"`
	Phone        *string          `json:"phone"`
	PasswordHash string           `json:"password_hash"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetUserAuthByPhone(ctx context.Context, phone *string) (GetUserAuthByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserAuthByPhone, phone)
	var i GetUserAuthByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
