// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Files struct {
	ID               uuid.UUID `json:"id"`
	UserID           uuid.UUID `json:"user_id"`
	FileUri          string    `json:"file_uri"`
	FileThumbnailUri string    `json:"file_thumbnail_uri"`
	CreatedAt        time.Time `json:"created_at"`
}
