// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (Files, error)
	DeleteFile(ctx context.Context, id uuid.UUID) error
	GetFile(ctx context.Context, id uuid.UUID) (Files, error)
	GetFilesByID(ctx context.Context, dollar_1 []uuid.UUID) ([]Files, error)
	GetFilesByUserID(ctx context.Context, userID uuid.UUID) ([]Files, error)
}

var _ Querier = (*Queries)(nil)
