FROM golang:1.25-alpine

# Install Air for live reload
RUN go install github.com/air-verse/air@latest

WORKDIR /app

# Copy auth's go.mod + only needed package
COPY services/auth/go.mod services/auth/go.sum services/auth/
COPY services/auth/pkg/ services/auth/pkg/
COPY services/core/ services/core/

# Copy only the service directory (context is root directory)
COPY services/files/ services/files/

# Move to service directory and download dependencies
WORKDIR /app/services/files
RUN go mod download

# Default command
CMD ["air"]