// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CheckExistedUserAuthByEmail(ctx context.Context, email string) (bool, error)
	CheckPhoneExists(ctx context.Context, phone string) (bool, error)
	CreateUserAuth(ctx context.Context, arg CreateUserAuthParams) (CreateUserAuthRow, error)
	GetUserAuthByEmail(ctx context.Context, email string) (GetUserAuthByEmailRow, error)
	GetUserAuthByPhone(ctx context.Context, phone string) (GetUserAuthByPhoneRow, error)
	RegisterWithEmail(ctx context.Context, arg RegisterWithEmailParams) (RegisterWithEmailRow, error)
}

var _ Querier = (*Queries)(nil)
